baseURL = '/'
languageCode = 'en-us'
title = 'New Frameworks to Preserve and Publish Born-Digital Art'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

# [markup]
  # [markup.goldmark]
    # [markup.goldmark.renderer]
      #unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/

[params]
    [params.footer]
        copyright = "A project of the [Center for Digital Scholarship](https://library.brown.edu/create/cds/), Brown University Library"

    [params.docs]
        darkMode = true
        themeColor = 'blue' # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan
        titleIcon = true
        navDesc = true
        navDescTrunc = 150
        listDescTrunc = 150
        extLinkNewTab = false
        lastMod = true

[menu]
    [[menu.primary]]
        name  = "Artists"
        url = "docs/artists"
        identifier = "artists"
        weight = 10

    [[menu.primary]]
        name  = "Contact"
        url = "docs/contact"
        identifier = "contact"
        weight = 20

    [[menu.primary]]
        name  = "Press"
        url = "docs/press"
        identifier = "press"
        weight = 30

    [[menu.primary]]
        name  = "Process"
        url = "docs/process"
        identifier = "process"
        weight = 40

    [[menu.primary]]
        name  = "Future Directions"
        url = "docs/future-directions"
        identifier = "future"
        weight = 50

    [[menu.primary]]
        name  = "Meet the Team"
        url = "docs/team"
        identifier = "team"
        weight = 60
