name: deploy to reclaim
on: 
  push:
    branches: [ master ]

jobs:
  deploy:
    if: github.repository_id == '707771755'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo -e production --minify

      - name: List output files
        run: ls public

      - name: newdeploy
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          # updated 29 April 2025
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
      #    uploads: |
      #      ./public => /home/newframe/public_html/
          uploads: |
            ./public => /home/newframe/www/
          delete: 'true'
