name: 'Generate and deploy'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Do a git checkout including submodules
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Generate and deploy website
        uses: Brown-University-Library/hugo-rsync-deployment@master
        env:
          VPS_DEPLOY_KEY: ${{ secrets.GHRECLAIM }}
          VPS_DEPLOY_USER: newframe
          VPS_DEPLOY_HOST: newframeworks.digitalscholarship.brown.edu
          VPS_DEPLOY_DEST: /home/newframe/www/
        with:
          hugo-arguments: '--minify'
          rsync-arguments: '--archive --compress --xattrs --delete'
